### PR TITLE
#29 fix bugs occurred while testing

### LINKED ISSUE #29: Fix bugs while testing
FAILED tests/test_DataAugmenterInternally.py::test_augment_column_norm_2 - AssertionError: KS criteria
FAILED tests/test_DataAugmenterNLP.py::test_augment_wordnet - TypeError: tokens: expected a list of strings, got a string
FAILED tests/test_DataAugmenterNLP.py::test_augment_emb_2 - OSError: [E050] Can't find model 'en_core_web_md'. It doesn't seem to be a Python package or a valid path to a data directory.

### PR DESCRIPTION
**Pull request by AlexKay28**
1. FAILED tests/test_DataAugmenterInternally.py::test_augment_column_norm_2 - AssertionError: KS criteria
2. FAILED tests/test_DataAugmenterNLP.py::test_augment_wordnet - TypeError: tokens: expected a list of strings, got a string
3. FAILED tests/test_DataAugmenterNLP.py::test_augment_emb_2 - OSError: [E050] Can't find model 'en_core_web_md'. It doesn't seem to be a Python package or a valid path to a data directory.

was solved:
1. increased number of examples, set random seed value in test, more setting more obvious params (prior knowledge) and fixed some shitty code in DataAugmenterInternally
2. reduced nltk version
3. model wasn't before running using command   `python -m spacy download en_core_web_md`

### CODE REVIEW

**Comment by joein** [comment]
We need a convenient way to test, so at least we need place pytest and other test dependencies in the requirements  (and I'd like to have it in a separate requirements.txt in the test dir because we don't want to pull pytest into production environment)

**Comment by joein** [comment]
Unfortunately, I can't launch the tests due to numpy incompatibility.
Maybe you actually use different library versions?

Here is my traceback after launching pytest
image

And here is a [link](https://github.com/scipy/scipy/issues/14541) for related issue, so I think we should update numpy to at least 1.19

**Comment by AlexKay28** [comment]
> We need a convenient way to test, so at least we need to place pytest and other test dependencies in the requirements (and I'd like to have it in a separate requirements.txt in the test dir because we don't want to pull pytest into the production environment)

hm. sounds reasonable, but I'm not quite sure how to deal with it.. I mean, should we create a separate environment for it? so then we can define two envs - the "dev" environment and the "main" one.
Can you check the most convenient way of implementation and create an issue? Will see how to do this

**Comment by AlexKay28** [comment]
> Unfortunately, I can't launch the tests due to numpy incompatibility. Maybe you actually use different library versions?
> 
> Here is my traceback after launching pytest image
> 
> And here is a [link](https://github.com/scipy/scipy/issues/14541) for related issue, so I think we should update numpy to at least 1.19

numpy version was downgraded to 0.17
(about your problem, I did not have any problems with versions, but if it occurred with you, so it may happen with someone else)

**Comment by joein** [comment]
it's a bit confusing that we develop a new package and downgrading versions of dependencies, maybe we should find another workaround to use more recent versions? It is about numpy and nltk versions
We can use separate requirements into two parts
E.g. one in the root has all prod dependencies and the second one in the tests dir has only additions to prod

**Comment by AlexKay28** [comment]
> it's a bit confusing that we develop a new package and downgrading versions of dependencies, maybe we should find another workaround to use more recent versions? It is about numpy and nltk versions We can use separate requirements into two parts E.g. one in the root has all prod dependencies and the second one in the tests dir has only additions to prod

about versions: I guess it's better not to restrict users in the package version. I strongly believe that if we use the latest version of each package from requirements.txt it will lead users to versions compatibility problems too often.
about requirements: maybe it's ok) I have asked you to create an issue as a maintainer before -"Can you check the most convenient way of implementation and create an issue? Will see how to do this"

**Comment by joein** [comment]
What do you mean about "it's better not to restrict users in the package versions?"
I said that it's a bit odd that we can't use recent versions of numpy and we have to use version from 2019 at the moment. Shouldn't we upgrade our interface or something to use younger versions of third-party libraries and receive modern functionality / bug fixes / etc. ?

**Comment by AlexKay28** [comment]
> What do you mean about "it's better not to restrict users in the package versions?" I said that it's a bit odd that we can't use recent versions of numpy and we have to use version from 2019 at the moment. Shouldn't we upgrade our interface or something to use younger versions of third-party libraries and receive modern functionality / bug fixes / etc. ?

why we cant? we can
I suppose that the latest packages version extends previous functionality in general (yes they fix bugs but in another proportion), so it means it is closer to the restriction of possible versions. You can check real settings while using the package in setup.py
Actually, I guess it's not arguing a topic now, but in some controversial terms, I agree with you but in  the other ones, I don't

**Comment by AlexKay28** [comment]
I'm going to create a task to create the right tox.ini because of its direct definition 

> Tox is a tool that creates virtual environments, and installs the configured dependencies for those environments, for the purpose of testing a Python package

**Pull request merged**
